Limit maximum file path name for Windows compatibility
woven-planet/go-zserio pull request #105
Opened 2022-10-07 06:23 UTC by PhilippVoigt

I would like to propose a solution for generating source files on or for use on Windows where we face a hard limit of 260 characters for the entire file path. The problem most commonly arises from complex template types for which all template type names are appended to the create a unique instantiated name.

Our first attempt was to shorten the the instantiated name itself which could likely lead to conflicts with similar-looking template types. Instead we would like to propose limiting the length of the final *.go file name, which in Go are not relevant for imports and therefore don't affect code generation. To ensure uniqueness we propose adding indexed suffixes, i.e. _*_idx.go_ to the file name as needed. We've tested the approach for our own zserio schemas, which might differ from yours.

I'm curious to hear your thoughts and concerns about this change.

Philipp Voigt (<philipp.voigt@mercedes-benz.com>) on behalf of Mercedes-Benz Tech Innovation GmbH.
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

2022-10-07 12:43 UTC, wichert requested changes
Thanks for this @PhilippVoigt ! It looks like this will fix #95.

I think it makes sense to enable this by default, to prevent unexpected breakage on windows machines.

2022-10-07 12:43 UTC, wichert commented on internal/cli/generate.go
> +	generateCmd.Flags().IntVar(&maxPathLength, "maxlength", generator.DefaultMaxPathLength, "Limit path length to the given number of characters")
I would prefer to have a single flag to control this. For example something like:

```suggestion
	generateCmd.Flags().IntVar(&maxPathLength, "max-path-length", generator.DefaultMaxPathLength, "Maximum length of filename. Set to 0 for no limit")
```

2022-10-08 18:37 UTC, wichert approved these changes

2022-10-08 18:43 UTC, wichert requested changes
@PhilippVoigt There is a new failing teston ubuntu-latest now. Are you able to fix that one?

2022-10-10 04:28 UTC, PhilippVoigt commented
I'm still unable to get Bazel working on my Mac, that's why I did not detect this earlier. But the individual tests now succeed locally with a minimal change.

2022-10-10 07:15 UTC, wichert approved these changes

2022-10-10 07:16 UTC, wichert commented
Thanks for the quick fix, especially this early in the day!

2022-10-10 07:16 UTC, merged